language: cpp
dist: trusty
osx_image: xcode8.2

matrix:
  include:
    - os : linux
      compiler: g++
    - os: osx
      before_install:
        - brew install cmake

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest
