language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os : linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - os : linux
      compiler: clang++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - os: osx
      osx_image: xcode8.2
      before_install:
        - brew install cmake
        - brew install llvm
        - brew link llvm --force

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
  - make
  - ctest
